baseURL = 'https://lien-chu.github.io/IncubatorBlog.io/'
languageCode = 'en-us'
title = '.Net Programmer Incubator'
theme = "arabica"
subtitle = "A blog about .Net programming"
paginate = 5
disqusShortname = "dotnetprogrammerincubator"

[params]
  author = "Vicky"
  description = "A blog about .Net programming"
  keywords = ["dotnet", "programming", "blog"]
  twitter = "dotnetprogrammer"
  github = "dotnetprogrammer"
  linkedin = "dotnetprogrammer"
  facebook = "dotnetprogrammer"



