baseURL = 'https://lien-chu.github.io/IncubatorBlog.io/'
languageCode = 'en-us'
title = '.Net Programmer Incubator'
theme = "arabica"
subtitle = "A blog about .Net programming"
paginate = 5
disqusShortname = "dotnetprogrammerincubator"
hasCJKLanguage = true

[menu]

  [[menu.main]]
  identifier = "All Posts"
    name = "All Posts"
    url = "/post/"
    weight = 2

  [[menu.main]]
  identifier = "mytips"
  name = "Tips"
  url = "/tags/tips/"
  weight = 3

   [[menu.main]]
  identifier = "ASP.NET Core MVC"
  name = "ASP.NET Core MVC"
  url = "/tags/asp.net-core-mvc/"
  weight = 3

[params]
  author = "Vicky Kulumanga"
  SEOTitle = "It's a place to learning .Net | Incubator Blog"
  description = "Let us grow together"
  rss            = "false"
  email          = "vickykilumanga@gmail.com"
  #facebook      = ""
  linkedin       = "in/lien-chu-h-85a78b238"
  #instagram     = ""
  github         = "Lien-Chu"


